# -*- coding: utf-8 -*-
"""Grupo 7 - Caderno 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uGwiPIevXGgxYC4Fv23Po_xmEw7BM6Ni

**Primeiro, devemos importar os dados do CSV, utilizando a biblioteca pandas. Logo após, definir as funções que carregam uma coluna para um módulo e depois, definir a função que imprime este módulo. Com esses dados, podemos calcular a média de cada vetor criado. As colunas selecionadas foram: Ano e BPM.**
"""

#Carregando os arquivos através da biblioteca pandas
import pandas as pd
codigo="1RaGSeaaFDoBcOjV3j9s0rRYZaY1kalOz"
arquivo="https://drive.google.com/u/3/uc?id="+codigo+"&export=download"
filmes = pd.read_csv(arquivo, sep=",", encoding="ISO-8859-1")
#Definindo as Funções que serão utilizadas
def CarregaAno(Vet,filmes):
  for ind in range(20):   
    filme = filmes.loc[ind]     
    Vet.append(filme.year)    

def ImprimeVetAno(Vet):
    print("Os anos disponibilizados no vetor são:")
    N=len(Vet)
    for ind in range(N):
      print(Vet[ind], end=" |")

def MediaVet(Vet):
  n=0
  for i in range(20):
    n=n+Vet[i]
  media=n/20
  return (media)

def CarregaBPM(Vet,filmes):
  for ind in range(20):   
    filme = filmes.loc[ind]      
    Vet.append(filme.bpm)    

def ImprimeVetBpm(Vet):
    print("Os valores de BPM disponibilizados no vetor são:")
    N=len(Vet)
    for ind in range(N):
      print(Vet[ind], end=" |")


#========================================================================================================Programa Principal===================================================================================================================
VetBpm=[]
VetAno=[]
CarregaAno(VetAno, filmes)
CarregaBPM(VetBpm, filmes)
media=MediaVet(VetAno)
media2=MediaVet(VetBpm)
ImprimeVetAno(VetAno)
print("")
print("O valor médio do Vetor relacionado à coluna ano é: %.1f"%media)
print("")
ImprimeVetBpm(VetBpm)
print("")
print("O valor médio do Vetor relacionado à coluna Bpm é: %.2f"%media2)